version: '3.3'
services:

    # Runs the bitcoind service, and exposes itself to the lnd_service. 
    bitcoind_service:
        image: bitcoind_image
        build:
            context: bitcoind/
        container_name: bitcoind_container
        volumes:
            - ./bitcoind/bitcoin_data:/root/.bitcoin
        restart: always
        entrypoint: ["./start-bitcoind.sh"]


    # Runs the lnd service.
    lnd_service:
        image: lnd_image
        build:
            context: lnd/
        container_name: lnd_container
        volumes:
          - ./lnd/lnd_data:/root/.lnd
        depends_on:
            - bitcoind_service
        restart: always
        entrypoint: ["./start-lnd.sh"]


    # Runs rethinkdb.
    rethink_service:
        image: rethink_image
        build:
            context: rethink/
        container_name: rethink_container
        volumes:
            - ./rethink/rethink_data:/root/.rethink
        depends_on:
            - bitcoind_service
            - lnd_service
        restart: always
        entrypoint: ["./start-rethink.sh"]


    # Runs AO.
    ao_service:
        image: ao_image
        build:
            context: ao/
        container_name: ao_container
        volumes:
            - ./lnd/lnd_data:/root/.lnd
        depends_on:
            - bitcoind_service
            - lnd_service
            - rethink_service
        restart: always
        entrypoint: ["./start-ao.sh"]
